### ISSUE TITLE
Fix 404 Not Found on GitHub API request

### ISSUE THREAD

**Issue by JulianPrieber** [nekosheen/linkstack-themes#1]
Please make sure all themes have a proper release candidate.
An actual release with a tag.

For some reason, marking releases as "pre-release" makes the GitHub API we use for theme downloads unable to find the latest release.

These themes currently error out when downloading via https://t.linkstack.org/

<img width="711" alt="chrome_On7vBxdEbF" src="https://github.com/user-attachments/assets/2733f4e8-fa1a-4143-9c79-0afdd5009598">

<br>

<br>

```
Warning: file_get_contents(https://api.github.com/repos/nekosheen/PaperBold/releases/latest): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
```

<br>

## How to fix:

**For each theme, create a new release with a tag and leave the release title blank. Do not mark it as "pre-release".**

---

<br>
<br>
<br>

Thank you so much for putting your time and effort into this! We'd love to include more themes on the list.

**Comment by JulianPrieber** [comment]
We currently look up the latest release version via releases.
We could switch to tags, not sure if that's the best solution here.

It's not really mentioned in the theme docs, we just noticed this.

**Comment by nekosheen** [comment]
OK Julian, thank you I will make them a release
